# Generated by Django 5.2.1 on 2025-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('processor', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
