# Generated by Django 5.2.1 on 2025-05-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',)},
        ),
    ]
